### ISSUE TITLE
No service on Visible (Verizon)

### ISSUE THREAD

**Issue by daradib** [GrapheneOS/os_issue_tracker#153] opened 2019-11-06 10:26 UTC
I ported my number to Visible (MVNO owned by Verizon) and now have no service. SIM works in a stock Pixel 3 XL but not GrapheneOS. To my knowledge, Visible only operates on Verizon LTE, so VoLTE might be required for voice calls.

## Behavior on stock

Mobile network settings reports carrier Visible. There is a single access point configured/enabled with APN set to VSBLINTERNET and APN type default,supl,dun. `*#*#4636#*#*` reports `Voice Service: In Service`, `Data Service: Connected`, `Voice Network Type: LTE`, `Data Network Type: LTE`, and VoLTE Provisioned is blue and enabled.

## Behavior on GrapheneOS

Mobile network settings reports carrier Verizon, VoLTE enabled. There is a single access point configured but not enabled with APN set to VZWINTERNET. (Presumably there are others but AOSP sets [user_visible="false"](https://android.googlesource.com/device/sample/+/master/etc/apns-full-conf.xml#14526).) `*#*#4636#*#*` reports `Voice Service: Emergency Calls Only`, `Data Service: Disconnected`, `Voice Network Type: Unknown`, `Data Network Type: Unknown`, and VoLTE Provisioned is enabled but grayed out. Although APN editing is disabled, I am able to [add APNs using a workaround](https://forum.xda-developers.com/showpost.php?p=75157321&postcount=14). However, I still don't get service and I'm not sure incorrect APN settings would be the cause of no service.

## CarrierConfig

Perhaps these problems are caused by carrier config included in stock but not AOSP (anestisb/android-prepare-vendor#78)? [`CarrierConfig/assets/carrier_config_mccmnc_311480.xml`](https://android.googlesource.com/platform/packages/apps/CarrierConfig/+/refs/heads/master/assets/carrier_config_mccmnc_311480.xml) and [`device/sample/etc/apns-full-conf.xml`](https://android.googlesource.com/device/sample/+/master/etc/apns-full-conf.xml#14544) do not mention Visible but [`platform/packages/providers/TelephonyProvider/assets/carrier_list.textpb`](https://android.googlesource.com/platform/packages/providers/TelephonyProvider/+/master/assets/carrier_list.textpb#8316) does.

I extracted the crosshatch image and took a look at CarrierSettings.apk. Visible is defined in `others.pb`. `protoc --decode_raw CarrierSettings/assets/others.pb` shows VSBLIMS, VSBLADMIN, VSBLINTERNET, VSBLAPP. On other phones (Samsung?) [these APNs are listed in /system/etc/apns-config.xml](https://www.reddit.com/r/Visible/comments/dob0ar/apn_information/).

Beside APNs, the only difference from `verizon_us.pb` is changing "carrier_name_string" and "cdma_home_registered_plmn_name_string" from "Verizon" to "Visible" and deleting some keys (carrier_wifi_string_array, ci_action_on_sys_update_bool, ci_action_on_sys_update_extra_string, ci_action_on_sys_update_extra_val_string, ci_action_on_sys_update_intent_string, config_ims_package_override_string, convert_cdma_caller_id_mmi_codes_while_roaming_on_3gpp_bool, default_vm_number_string, dial_string_replace_string_array, emailGatewayNumber).

## adb logs

Some excerpts from adb logcat:

    E DefaultPermGrantPolicy: PackageNot found: com.verizon.mips.services
    E DefaultPermGrantPolicy: PackageNot found: com.qualcomm.ltebc_vzw
    E DefaultPermGrantPolicy: PackageNot found: com.google.android.wfcactivation
    E RTPServiceImpl:  Couldn't register with Diag LSM, errno: 25
    E Diag_Lib: [IMS_FATAL]| 2539 |SingoConfig::Init()| FATAL error cannot recover: Unable to get DPLConfig
    E Diag_Lib: [IMS_FATAL]| 2539 |InitServiceModules | pSingoConfig->Init() Failed
    D MccTable: updateMccMncConfiguration mccmnc='311480
    D MccTable: updateMccMncConfiguration: mcc=311, mnc=480
    D MccTable: updateMccMncConfiguration updateConfig config={0.0 311mcc480mnc ?localeList ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?ldr ?wideColorGamut ?orien ?uimode ?night ?touch ?keyb/?/? ?nav/? winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=null mWindowingMode=undefined mDisplayWindowingMode=undefined mActivityType=undefined mAlwaysOnTop=undefined mRotation=undefined}}
    E LocSvc_APIClientBase: onCtrlCollectiveResponseCb:208] ERROR: 3 ID: 28
    E StatusBarSignalPolicy: Unexpected subscription 2
    W Telecom : PhoneAccountRegistrar: Trying to set nonexistent default outgoing ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0}: [****]
    E LocSvc_APIClientBase: onCtrlCollectiveResponseCb:208] ERROR: 3 ID: 36
    V KeyguardUpdateMonitor: SubInfo:{id=2, iccId=[****] simSlotIndex=0 carrierId=2146 displayName=Verizon carrierName= nameSource=3 iconTint=-16746133 mNumber=[****] dataRoaming=1 iconBitmap=android.graphics.Bitmap@d740853 mcc 311 mnc 480mCountryIso=us isEmbedded false accessRules null cardString=[****] cardId=1 isOpportunistic false mGroupUUID=null mIsGroupDisabled=false profileClass=-1 ehplmns = [311480] hplmns = [311480] subscriptionType=0 mGroupOwner=null}
    I tftp_server: pid=936 tid=936 tftp-server : INF :[tftp_server.c, 659] rcvd request [1] [73] [1] [0] [107]
    I tftp_server: pid=936 tid=2663 tftp-server : INF :[tftp_server_utils.c, 113] file [readwrite/mcfg.tmp] : [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
    I tftp_server: pid=936 tid=2663 tftp-server : INF :[tftp_server.c, 1202] OACK options : [7680, 1000, 0, 10, 0, 0, 0, 0]
    I tftp_server: pid=936 tid=2663 tftp-server : INF :[tftp_os_la.c, 63] open : [-1] [-1] [384] [0] [/vendor/rfs/msm/mpss/readwrite/mcfg.tmp]
    E tftp_server: pid=936 tid=2663 tftp-server : ERR :[tftp_os_la.c, 70] open failed: [2] [No such file or directory]
    E tftp_server: pid=936 tid=2663 tftp-server : ERR :[tftp_server.c, 1698] open failed : [-2] [Unknown error -2]
    E tftp_server: pid=936 tid=2663 tftp-server : ERR :[tftp_protocol.c, 1229] sending error-pkt. Code = 1, Msg = Err=2 String=No such file or directory

**Comment by daradib** [comment] 2019-11-06 14:47
I managed to fix service and data but not voice, SMS, or MMS.

    $ adb shell am start -a android.intent.action.INSERT content://telephony/carriers --ei simId -1

    APN: VSBLINTERNET
    MCC: 311
    MNV: 480
    APN type: default,supl
    APN protocol: IPv4/IPv6
    MVNO type: GID
    MVNO value: BAE1000000000000

This replaces the existing VZWINTERNET profile which is locked. Save and toggle airplane mode.

If I add VSBLIMS with APN type "ims,ia" based on CarrierSettings, I lose service again. The ia (initial attach) part is seemingly incompatible. Perhaps this depends on one of the proprietary apps that GrapheneOS does not include (e.g., com.google.android.wfcactivation)?

**Comment by daradib** [comment] 2019-11-07 07:46
CarrierSettings for both Verizon and Visible reference `com.google.android.carriersetup` under `carrier_setup_app_string` and `carrier_app_wake_signal_config`. I guess IMS/VoLTE provisioning requires that priv-app. I don't see a way to test different carrier settings without root or reflashing.

Even though it wouldn't be privileged, I tried installing it:

    $ adb install CarrierSetup.apk
    Performing Streamed Install
    adb: failed to install CarrierSetup.apk: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package com.google.android.carriersetup requires unavailable shared library com.verizon.provider; failing!]

`/system/etc/permissions/com.verizon.provider.xml` in turn references `/system/framework/VerizonUnifiedSettings.jar`. I see a lot of mentions of volte in `/system/framework/oat/arm64/VerizonUnifiedSettings.vdex`. Both of these files are included via android-prepare-vendor.

Any suggestions?

**Comment by daradib** [comment] 2019-11-10 17:54
Service including voice (no 3G, only VoLTE) is working fine out of the box on the same phone flashed with AOSP 10.0.0_r10. No Verizon blobs either, just using the default naked configuration group in android-prepare-vendor without changes from the GrapheneOS fork.

    repo init -u https://android.googlesource.com/platform/manifest -b android-10.0.0_r10
    repo sync -j4 -qc
    source build/envsetup.sh
    lunch aosp_crosshatch-userdebug
    cd vendor
    git clone https://github.com/GrapheneOS/android-prepare-vendor.git
    cd ..
    vendor/android-prepare-vendor/execute-all.sh -d crosshatch -b QP1A.191105.003 -o vendor/android-prepare-vendor
    mkdir -p vendor/google_devices
    rm -rf vendor/google_devices/crosshatch
    mv vendor/android-prepare-vendor/crosshatch/qp1a.191105.003/vendor/google_devices/* vendor/google_devices/
    eatmydata make -j4
    ANDROID_PRODUCT_OUT=out/target/product/crosshatch fastboot flashall -w

**Comment by thestinger** [comment] 2019-11-13 18:09
If it works without the GrapheneOS changes, someone will need to narrow down the cause.

**Comment by thestinger** [comment] 2019-11-13 18:10
If it works without the GrapheneOS changes, someone with access to this carrier will need to narrow down the cause. I cannot work on the issue myself.

**Comment by thestinger** [comment] 2019-11-13 18:12
It's possible that it's caused by a problem like https://github.com/GrapheneOS/os_issue_tracker/issues/133. There are many areas where help is required. It could also be an unknown compatibility issue not yet described like that on the issue tracker. Someone with access to this carrier will need to narrow down which feature(s) cause the compatibility issue, determine why and then work towards resolving it.

**Comment by ziddey** [comment] 2019-12-21 23:28
@daradib you ever figure this out? I'm trying to get visible working on a ph1 and am seeing the same behavior. I can get data and mms working with the appropriate apn settings. VSBLIMS with type `ia` is a no-go, and no volte without

**Comment by daradib** [comment] 2020-01-01 22:12
@thestinger I tried removing the exec spawning block from [ZygoteConnection.java](https://github.com/GrapheneOS/platform_frameworks_base/commit/16636ae9768a3611ac6e15293c557c22d7173a38#diff-393026fe9833a6bb438caa5cb8b3ae69), but unfortunately the issue persists. I also tried reverting "[enable Verizon visual voicemail support](https://github.com/GrapheneOS/platform_packages_services_Telephony/commit/8241a7eb2282f0868c88bbfb8211215ca9e3ad73)" and Cloudflare DNS changes in platform_frameworks_base. Are there other features/commits you recommend that I try reverting to help narrow this down? Is IMS/VoLTE known to work for any carrier?

@ziddey Visible works on the same Pixel 3 XL running AOSP. IMS/VoLTE works with or without changes to APN settings, presumably VZWIMS which is included in AOSP works too. The PH-1 might be a different issue.

**Comment by djmwj** [comment] 2020-02-04 05:30
@daradib I have been experimenting with this as well. When you manually added the VSBLINTERNET APN were you actually able to complete the ping tests in the *#*#4636#*#* menu? I have made the same changes but it cannot pass the ping test. What is very interesting is that i can go to google.com in Chrome or firefox, but cannot go to other domains or connect via a vpn. Have you experienced similar with the data connection you were able to establish?

**Comment by danielk43** [comment] 2020-02-19 01:10
@daradib So close to getting this to work, at least in a MVP sense. I can add the APNs from the Reddit link to a build and the SIM will connect. Voice, Data, SMS, MMS - sending and receiving all seem to work. Hotspot works, and the IPv4 ping test passes. Details [here](https://gist.github.com/danielk43/d3ed74f7f81b27c228864f8f06489851).

The only problem is that during voice calls (and in visual voicemail), the screen goes black and is completely inaccessible until the call/msg has ended.

More clues: lineage-17.1 unofficial builds will pull down the carrier config automatically (without having to adjust apns.xml), but with the same black screen problem. Same behavior whether Gapps or MicroG. I hope this can help narrow down the cause and get closer to a solution.

**Comment by thestinger** [comment] 2020-02-19 01:27
The black screen issue just sounds like you have a defective screen protector blocking the proximity sensor rather than a software issue. The AOSP values for the proximity sensor might be tuned differently than the stock OS ones.

**Comment by danielk43** [comment] 2020-02-19 01:37
@thestinger Appreciate the fast response and tip! Unfortunately it didn't work, after removing the screen protector and case, restarting, and making another call. I'll look into the AOSP proximity sensor settings, maybe some testing there would reveal something.

**Comment by danielk43** [comment] 2020-02-19 04:28
@thestinger you are right. My phone itself is the problem, even with the stock OS. The apn.xml changes should work

**Comment by Adam-Adam-Adam** [comment] 2020-04-28 12:53
Is there a way to modify APN.XML via adb or during the flash process, or does it require a complete build?

**Comment by thestinger** [comment] 2020-04-28 13:09
> Is there a way to modify APN.XML via adb or during the flash process

No.

> or does it require a complete build?

It can be updated out-of-band as part of updating the OS.

If people want this fixed, they need to help get these things set up the same way as the stock OS. There will never be any progress on it if people don't step up to help. I filed an issue about CarrierConfig for android-prepare-vendor *ages ago* and no one has stepped up to help. I got the work done myself for the original Pixel and Pixel XL that work was not redone for Android Pie or Android 10 and they're no longer supported. It can't always be me doing this kind of work and I've decided I won't be doing that kind of device maintenance anymore. The CarrierConfig resources are also not the only ones that need to be set up properly... This is why we'll be dropping support for all the devices without maintainers (currently, none have maintainers).

**Comment by thestinger** [comment] 2020-06-22 16:31
Someone with this carrier has to be willing to put in the effort to debug this by narrowing it down to a GrapheneOS feature and then figuring out why it happens. The first step is once again checking AOSP + android-prepare-vendor vs. GrapheneOS, followed by narrowing down the feature causing the issue. If there isn't interest in working on this, I'll be closing it. Carrier issues are only valid issues if someone with the carrier is an active developer.

**Comment by daradib** [comment] 2020-06-22 21:24
Past observations:

 * AOSP + android-prepare-vendor (GrapheneOS fork)
   * VoLTE works if the correct APNs (at minimum, VSBLINTERNET) were manually added during the first boot.
   * If the APNs were added after a reboot, VoLTE never worked, even after resetting network settings and app preferences - needed to factory reset and add the APNs during the first boot.
 * Stock
   * VoLTE works. CarrierSettings already includes the APNs.
 * GrapheneOS
   * Unlike AOSP, VoLTE didn't work even if APNs were manually added during the first boot.
   * VoLTE worked when @danielk43 included the APNs in build.

I'm not sure why GrapheneOS first boot behavior is different from AOSP, but I think including the APN settings in the build as stock does seems to be the best solution.

@thestinger where should we include these additional APN settings. `overlay/packages/apps/CarrierConfig/res/xml/vendor.xml` for every device repo? `frameworks/base/core/res/res/xml/apns.xml`?

**Comment by thestinger** [comment] 2020-06-22 21:31
It probably makes sense to do it per-device, based on copying the standard configuration. Keep in mind that we don't bundle all the same carrier apps though, so some entries will need to be altered based on that. The best way to do it would be extracting this, committing that unaltered, and then doing follow-up commits with alterations.

**Comment by daradib** [comment] 2020-06-27 20:29
I confirmed that adding the APNs to `frameworks/base/core/res/res/xml/apns.xml` works, thanks @danielk43.

@thestinger do you still suggest copying [`device/sample/etc/apns-full-conf.xml`](https://android.googlesource.com/device/sample/+/master/etc/apns-full-conf.xml) to every device repo and making these changes there? No changes to CarrierConfig were needed for VoLTE so we don't need to worry about carrier apps.

[Converted from CarrierSettings](https://github.com/daradib/carriersettings-extractor):

      <apn carrier="Visible"
          mcc="311"
          mnc="480"
          apn="VSBLIMS"
          authtype="0"
          type="ia,ims"
          protocol="IPV4V6"
          roaming_protocol="IPV6"
          bearer_bitmask="1|2|3|9|10|11|13|14|15|18"
          profile_id="2"
          modem_cognitive="true"
          max_conns="20"
          max_conns_time="300"
          mvno_type="gid"
          mvno_match_data="BAE1000000000000"
          user_visible="false"
      />

      <apn carrier="Visible"
          mcc="311"
          mnc="480"
          apn="VSBLADMIN"
          authtype="0"
          type="fota"
          protocol="IPV4V6"
          roaming_protocol="IP"
          bearer_bitmask="1|2|3|9|10|11|13|14|15|18"
          profile_id="3"
          modem_cognitive="true"
          max_conns="20"
          max_conns_time="300"
          mvno_type="gid"
          mvno_match_data="BAE1000000000000"
          user_visible="false"
      />

      <apn carrier="Visible"
          mcc="311"
          mnc="480"
          apn="VSBLINTERNET"
          authtype="0"
          type="default,supl,dun"
          protocol="IPV4V6"
          roaming_protocol="IP"
          bearer_bitmask="1|2|3|9|10|11|13|14|15|18"
          profile_id="0"
          modem_cognitive="true"
          max_conns="20"
          max_conns_time="300"
          mvno_type="gid"
          mvno_match_data="BAE1000000000000"
      />

      <apn carrier="Visible"
          mcc="311"
          mnc="480"
          apn="VSBLAPP"
          mmsc="http://mms.vtext.com/servlets/mms"
          authtype="0"
          type="cbs,mms"
          protocol="IPV4V6"
          roaming_protocol="IP"
          bearer_bitmask="1|2|3|9|10|11|13|14|15|18"
          profile_id="4"
          modem_cognitive="true"
          max_conns="20"
          max_conns_time="300"
          mvno_type="gid"
          mvno_match_data="BAE1000000000000"
          user_visible="false"
      />

**Closed** 2020-06-29 02:29 UTC
Labels: bug, upstream

**Comment by danielk43** [comment] 2020-06-29 14:20
Working on Crosshatch from a factory install.
Thank you @daradib, @thestinger !

For completeness, there is another thing the stock implementation is doing. Under Settings > Network & Internet > Mobile Network > Settings version, this is being populated as `visible_us-10000000413.2`. Mobile Network is also labeled as Verizon by default on GrapheneOS but that is user-editable and neither seem to have any bearing on the APNs.

All services are provisioned as expected, as shown by `*#*#4636#*#*`

**Comment by daradib** [comment] 2020-06-29 18:00
@danielk43 Stock bundles CarrierSettings for supplying both APN settings and carrier configuration, in place of `apns-conf.xml` and CarrierConfig, respectively. `visible_us-10000000413.2` seems to refer to the canonicalName and version of the protobuf file read by CarrierSettings. I'm not sure what the `.2` suffix refers to.

From [carriersettings-extractor](https://github.com/daradib/carriersettings-extractor) using the June image:

    $ protoc --decode=CarrierSettings carriersettings.proto < CarrierSettings/visible_us.pb
    canonicalName: "visible_us"
    version: 14000000425
    apns {
      ...
    }
    configs {
      ...
    }

With the PRs now merged, GrapheneOS uses the apns extracted from CarrierSettings, but not the configs (see [CarrierConfigManager.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/telephony/java/android/telephony/CarrierConfigManager.java)). AOSP already includes similar configs in [`carrier_config_carrierid_1839_Verizon-Wireless.xml`](https://android.googlesource.com/platform/packages/apps/CarrierConfig/+/refs/heads/master/assets/carrier_config_carrierid_1839_Verizon-Wireless.xml). VoLTE works with these.

CarrierSettings has additional settings, such as references to carrier apps that are included in stock but not AOSP/GrapheneOS as @thestinger mentioned:

      <string-array name="enable_apps_string_array" num="6">
        <item value="com.customermobile.preload.vzw"/>
        <item value="com.google.android.carrier.authdialog"/>
        <item value="com.verizon.llkagent"/>
        <item value="com.verizon.mips.services"/>
        <item value="com.verizon.services"/>
        <item value="com.vzw.apnlib"/>
      </string-array>

> All services are provisioned as expected, as shown by *#*#4636#*#*

Are they all marked as available under the overflow menu in top right -> IMS Service Status? Stock supports VoWiFi starting with the June update, but it doesn't work in AOSP/GrapheneOS. The vendor.xml generated by carriersettings-extractor includes this line that is not in AOSP: 

    <string name="wfc_emergency_address_carrier_app_string">com.google.android.wfcactivation/.VzwEmergencyAddressActivity</string>

Perhaps wifi calling requires com.google.android.wfcactivation (Carrier Setup) to first set the emergency address. Otherwise, perhaps some of the carrier apps.

**Comment by danielk43** [comment] 2020-06-29 18:25
Thanks for that valuable context, makes sense as other OSs do include Verizon apks/libs during build. IMS status is exactly as you described; VoLTE Available with VoWiFi, VC, UT Interface unavailable.

**Comment by beerisgood** [comment] 2020-07-03 07:56
Did i understand it correctly that you guys add VoLTE for provider "Verizon" and it work?
How we can add/ help with other APNs like for German networks ?

**Comment by danielk43** [comment] 2020-07-03 14:29
@beerisgood In the pull requests you can see a set of changes which 1) add apns-full-conf.xml, and 2) a small amount of code to ingest it. If your network is present in that file ([here](https://github.com/daradib/device_google_crosshatch/blob/af203101999afcefae357ab2926df20b1cb6a5da/apns-full-conf.xml), for example) and was not usable previously then it could also now connect to services supported by both GrapheneOS and the carrier.

If not, @daradib has created a [carriersettings-extractor](https://github.com/daradib/carriersettings-extractor) for devices such as Pixel which use protobuf binaries instead of AOSP-compatible xml files, that can be applied for the conversion if your network becomes included in the future.

You can build from the 10 (Development) branch, or wait a few days for any of the five devices mentioned to see if the current changes have also solved the issue for you, assuming it will be included in the next stable release.

**Comment by beerisgood** [comment] 2020-07-08 17:15
After the new update i still sadly can't enable VoLTE in phone hidden menu.
It doesn't matter if i switch to "LTE only" or not. Also my provider say that their isn't any problem on their side/ my side (SIM).

here a screenshot from the hidden menu:
![400025800199_165084](https://user-images.githubusercontent.com/9625159/86949690-515f5200-c14f-11ea-9563-22c509c67a32.jpg)

Any way to enable the greyed out buttons?

**Comment by daradib** [comment] 2020-07-12 22:53
The July update includes APNs from stock, but carrier configs are still sourced from AOSP.

@beerisgood What is your provider and MCC/MNC? AOSP apparently only allows VoLTE on Vodafone, not O2 and Telekom. Specifically, `carrier_volte_available_bool` is missing from [CarrierConfig assets](https://android.googlesource.com/platform/packages/apps/CarrierConfig/+/refs/heads/master/assets) (and [defaults to false](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/telephony/java/android/telephony/CarrierConfigManager.java)), but set to true in stock CarrierSettings depending on the MCC/MNC.

@thestinger previously reported the [same issue](https://github.com/anestisb/android-prepare-vendor/issues/78#issuecomment-320393596_) with Canadian carriers Fido and Rogers.

Suggestions:

1. Change the default of `carrier_volte_available_bool` to true. Will this break carriers that don't support VoLTE?

2. Overlay volte-specific configs from CarrierSettings in android-prepare-vendor.

3. Overlay all configs from CarrierSettings in android-prepare-vendor. Will we need to exclude references to carrier apps?

**Comment by beerisgood** [comment] 2020-07-13 06:43
@daradib my provider is "PremiumSim" which is a low cost provider who use the "o2" Network.
My MCC is 262 and MNC is 07.

Yeah you're right about Vodafone. A friend with Vodafone has VoLTE enabled in the hidden phone menu from my screenshot but VoLTE doesn't work for him. If he start a call, LTE switch to 3G / calling with "LTE only" stop immediately. Same case for me also.

**Comment by daradib** [comment] 2020-07-14 23:43
@beerisgood are you able to build GrapheneOS and test individual changes? There are unfortunately a lot of potential reasons for VoLTE to work in stock but not GrapheneOS. Besides APNs, which were updated in the last release, there could be missing carrier configs, blobs, or carrier apps.

If you would be able to test, can you identify which of these providers is yours? Each one is apparently assigned different settings in stock to compare with. For example, o2prepaid_de has `carrier_volte_available_bool` set to false.

From carrier_list.pb:

    entry {
      canonicalName: "o2prepaid_de"
      carrierId {
        mccMnc: "26207"
        imsi: "2620749"
      }
    }
    entry {
      canonicalName: "26207IMSI=26207500"
      carrierId {
        mccMnc: "26207"
        imsi: "26207500"
      }
    }
    entry {
      canonicalName: "26207IMSI=26207515"
      carrierId {
        mccMnc: "26207"
        imsi: "26207515"
      }
    }
    entry {
      canonicalName: "26207IMSI=26207520"
      carrierId {
        mccMnc: "26207"
        imsi: "26207520"
      }
    }
    entry {
      canonicalName: "26207SPN=ALICE"
      carrierId {
        mccMnc: "26207"
        spn: "ALICE"
      }
    }
    entry {
      canonicalName: "o2_de"
      carrierId {
        mccMnc: "26207"
      }
    }

**Comment by beerisgood** [comment] 2020-07-15 04:27
@daradib thanks! Sadly I can't build my own build.

**Comment by bkeys** [comment] 2020-08-15 20:10
Can anyone confirm if this is still an issue and who it is still effecting? Should someone in the US be able to use GrapheneOS and work with Visible out of the box?

**Comment by daradib** [comment] 2020-08-19 09:17
Not an issue anymore. As far as I'm aware, Visible should work out of
the box except for their mobile app and wifi calling.

The mobile app probably depends on Google Play Services and is only
needed to activate service. You can temporarily flash stock or use
another phone for activation.

Wifi calling probably depends on com.google.android.wfcactivation
(Carrier Setup) to provision the emergency address.

**Comment by thestinger** [comment] 2020-08-19 13:23
Alright, we can't support their app if it depends on Play Services. That's their problem.

**Comment by z00kus** [comment] 2020-09-18 21:39
Maybe I'm missing something, but I just can't get Visible to work with SMS/MMS at all on the 9/11 build of GrapheneOS.  From what I can see too from this thread, this can't apparently be fixed by using ADB to push the provided xml file above to the OS.

Is building it from scratch my only option at this point or have I overlooked something?  I noticed the four APN's originally through a thread on a thread on reddit in regards to activating a Galaxy Note 10 through the carrier and thought about taking that for a shot, only to realize that I couldn't edit the APN's at all on the device (Pixel 3a XL). 

The APN's were from what I could tell, the exact same ones used on this page though.

**Comment by daradib** [comment] 2020-09-18 21:58
@z00kus Hmm, that's strange. Can you try a different SMS/MMS app, for example, [using Signal](https://support.signal.org/hc/en-us/articles/360007321171-Can-I-send-SMS-MMS-with-Signal-)?

Otherwise, does it work on factory reset stock? Does it work on factory reset GrapheneOS? If you don't want to factory reset, you can try resetting APNs to default from the top right overflow menu or resetting wi-fi mobile bluetooth from System - Reset options, but even in stock only factory reset seems to properly reset all of the network settings.

You should be able to add APNs by using Activity Launcher from F-Droid to launch Settings - APNs, but I doubt that would help, since the APNs are already included (only VSBLINTERNET will be visible, the other three have user_visible set to false) and because adding APNs after a fresh install doesn't seem to trigger IMS properly (also affects AOSP and probably stock if it didn't include the APNs in CarrierSettings).

**Comment by z00kus** [comment] 2020-09-18 23:31
@daradib Did the factory reset and it still wasn't working at all which was pretty strange to me.  For the hell of it though, I reset the Wi-fi/Mobile/Bluetooth and everything seems to be working all of a sudden again.

Wanted to give you a heads up as well, I was able to add the APN's originally before reseting with Activity Launcher but it did _not_ help.  I'm not sure what caused the issue to be honest, but I'll update this again if it does pop up and maybe we can go deeper on the issue (If the issue persists obviously).

**Comment by daradib** [comment] 2020-09-21 22:26
@z00kus Glad you got it working. Maybe reconnecting to the cell network a few times helped. Visible often suggests [toggling airplane mode](https://www.reddit.com/r/Visible/comments/iujmz5/why_does_visible_occasionallylose_all_connection/), so it might have been a carrier issue.

**Comment by fearyncess** [comment] 2020-11-26 12:05
Due to the Google's upstream vendor firmware problem, many MVNO and other regions' ISP is not supported in Pixel for VoLTE because the vendor firmware doesn't provide the EFS cfg files for them.

eg. the mbn config list in Pixel 4 (sunfish) (extracted from sunfish-factory-2020.11.05.18)
```
fs@DiusSasye [ Desktop ] $ ls /mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/*/ -1
/mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/APAC/:
DCM
KDDI
Rakuten
Reliance
SBM

/mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/AUNZ/:
Optus
Telstra
Vodafone

/mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/common/:
WildCard

/mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/EU/:
Bouygues
DT
EE
H3G
Orange
SFR
Swisscom
TDC
Tele2
Telefonica
Telenor
Telia
TIM
Vodafone

/mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/NA/:
ATT
Bell
Rogers
Sprint
Telus
TMO
USCC
Verizon

/mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/Pixel/:
APAC
EU
NA
PTCRB
TestSIM

/mnt/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/generic/SEA/:
ChunghwaTel
FarEastOne
Singtel
StarHub
TM
```

**Comment by thestinger** [comment] 2020-11-26 12:11
A lot of configuration is provided via CarrierConfig which we're currently missing but are working on providing. We won't be able to provide it for Verizon due to them requiring a bunch of invasive proprietary vendor apps.

**Comment by meximan** [comment] 2021-09-04 15:34
I am thinking about getting Graphene OS with prepaid Verizon wireless and Pixel 6 ? So is grapheneOS working out of the box with verizon wireless or is this still an unresolved issue? (noob here)

**Comment by thestinger** [comment] 2021-09-04 19:39
It works fine.

**Comment by soulmist7** [comment] 2021-09-20 03:43
So does it work with Visible as well? I am about to buy a Pixel in order to get Graphene OS but don't want to be in trouble not being able to get my service to work...

**Comment by thestinger** [comment] 2021-09-20 07:33
Yes, it works. You might need to do some work to set it up properly but it does work.

**Comment by soulmist7** [comment] 2021-09-20 13:44
Thank you for the response stinger, I am not technically inclined in terms of working with phones and OS / manual app installations. I know a good amount about computers, but I'm not a coder. Do you think that I'd be able to figure things out based on resources others have written about online? (I haven't been able to find a good step by step guide and it has me concerned.)

**Comment by daradib** [comment] 2021-09-20 21:06
Visible works fine, with the exception of wifi calling, eSIM (potential workaround in #159), and possibly the app (which is only needed to activate service). No idea about 5G NR coverage though.

As for help installing and using GrapheneOS in general, I'd refer to the official documentation on the website and direct questions to the Matrix community.

**Comment by samuel-liff** [comment] 2021-10-03 15:49
> Visible works fine, with the exception of wifi calling, eSIM (potential workaround in #159), and possibly the app (which is only needed to activate service). No idea about 5G NR coverage though.
> 
> As for help installing and using GrapheneOS in general, I'd refer to the official documentation on the website and direct questions to the Matrix community.

@daradib, does Visible work as you described out-of-the-box with default APN settings or only after some manual configuring? Thanks.

**Comment by thestinger** [comment] 2021-10-03 16:26
It works fine.

**Comment by thestinger** [comment] 2021-10-03 16:26
5G also works fine with those carriers now.

**Comment by thestinger** [comment] 2021-10-22 02:17
There's a known issue for the Android 12 Beta with the Pixel 4a. That will be resolved in the next Beta.
