### ISSUE TITLE
Incoming calls while on a secondary profile will not use bluetooth headset, cannot switch to it during call either

### ISSUE THREAD

**Issue by matchboxbananasynergy** [GrapheneOS/os_issue_tracker#3174] opened 2024-02-03 14:10 UTC
On GrapheneOS, receiving an incoming call while on a secondary profile will not use a connected bluetooth headset, and will not allow you to switch to it during the call either.

This is not reproducible on stock OS.

On GrapheneOS, neither the AOSP dialer that comes with the OS, or Google's phone app will work properly.

To get an incoming call to show up via Google's phone app in a secondary profile, I had to install it in both owner *and* that secondary profile, and make it the default phone app in both profiles. The same issue with bluetooth persists even when the incoming call comes through Google's app.

The Bluetooth headset will show up as the selected input device on the in-call dialler UI, but despite this, the built-in mic will be used. Attempting to manually select any source will bring up the selection menu, but any selection made is ineffective and continues to display the Bluetooth headset as selected, with but with built in mic active.

---

**Possible causes**

1. This is an AOSP dialer bug, and the reason why Google's phone app won't work is because it needs to be the system dialer to work, not just the default phone app.
2. This is an AOSP OS bug that's been fixed on stock OS via an APEX module update or something similar, which has not yet been fixed in GrapheneOS as a result.

**Comment by add1989** [comment] 2024-03-18 20:08
Hi,

I can confirm that I'm also experiencing the same issue, ever since the upgrade to Android 14. Do we have any rough idea if/when anything is likely to happen on this?

**Comment by 5vmmvm** [comment] 2024-06-10 08:39
Same issue here

**Comment by User1966** [comment] 2024-06-20 14:50
I have seen this issue for months, on secondary profile.  Not tested on primary profile.

**Comment by User1966** [comment] 2024-07-02 13:20
@matchboxbananasynergy
@add1989 @5vmmvm 
FYI, I have a workaround

Environment: latest GrapheneOS and apps.

GIVEN you have an incoming call on the GrapheneOS telephone app on a secondary profile with a bluetooth headset connected
WHEN you select the hold button
AND select speaker OR phone from the dropdown
AND remove hold
THEN you switch to speaker/phone and can better hear the other person.

I can't seem to switch back to bluetooth headset at all, but less easy to test myself.
This workaround been working for a few weeks.

**Comment by Ariancabef** [comment] 2024-07-12 09:28
Same here, and it's really anoying!

Any fixing-timing expected?

**Comment by OstudaHanba** [comment] 2024-08-30 14:01
Same here

**Comment by schafskopf** [comment] 2024-08-31 18:24
Same Problem. Should I migrate to the owner profile or can this issue be fixed in future?
Anyway thank you for the great project - I would never use a stock rom again :-)

**Comment by ozankiratli** [comment] 2024-09-06 18:07
Experiencing the same issue. I think there is a bug tracker open on Google's end, too ([See here](https://issuetracker.google.com/issues/232112722)). It has been open for over 2 years and has received little attention; I'm guessing there are no plans to address it anytime soon. 

Not sure if this can be addressed by GrapheneOS at all, but I believe the solution to this bug may be more critical for GrapheneOS users than stock OS users, as GrapheneOS users are more likely to divide specific apps into specific profiles. For me, it's a problem when I'm using my phone in the car. As cars are very aggressive in data collection, I created a completely isolated profile with Android Auto installed. I don't get emails or messages, and I'd be happier if I could take calls when needed without using the owner profile.

**Comment by loufee** [comment] 2024-10-26 02:10
Today on a pixel 7 and on a secondary profile with a bluetooth headset I got a call. The notification sound or ringer was odd. One I'd not heard before from the phone. In fact, I didn't even realize it was a call coming in, I thought it was something in the youtube video I was watching. It acrually sounded just like a Win10 dialogue prompt. Short story long, when answered, the call came through my headset. First time this has happened so perhaps there's a fix or partial fix in place with the latest update?

**Comment by schafskopf** [comment] 2024-10-26 10:46
The update to Android15 has fixed the issue for me.
At least for the bluetooth headphones. I try it in my car soon.

**Closed as completed** 2024-10-26 12:40 UTC
Labels: bug, upstream
