### ISSUE TITLE
Greeny Screen

### ISSUE THREAD

**Issue by crueltekk** [GrapheneOS/os_issue_tracker#239] opened 2020-07-08 21:27 UTC
Screen get's greeny and starts flickering when I turn down brightness. As soon as I turn on energy saving that behavior stops.

Device: Pixel 4XL (coral)
Build: QQ3A.200705.002.2020.07.06.20

**Comment by thestinger** [comment] 2020-07-09 00:12
This sounds like a hardware issue. Not much that can be done about that.

**Comment by thestinger** [comment] 2020-07-09 00:13
What do you mean by energy saving though? Adaptive brightness?

I definitely can't reproduce this so it seems like a hardware issue, not a software one. Maybe try powering off fully and back on again.

**Comment by paintedman** [comment] 2020-07-09 06:58
It's not a hardware problem, and it's very easy to reproduce. 

Set dark theme, go into a dark room, and turn down the brightness. Then try to use your phone, and you can notice that flickering. 

>What do you mean by energy saving though?

I guess it's "Battery Saver" icon from notification bar. 

I also have this flickering issue, and for me enabling this option helps too.

**Comment by crueltekk** [comment] 2020-07-09 07:07
Okay still learning how to write issues that are usefull. So pls be kind with me.

> Set dark theme, go into a dark room, and turn down the brightness. Then try to use your phone, and you can notice that flickering. 
>  You do not even need to turn it down much. Around 50% is enough to get this bug.

> I guess it's "Battery Saver" icon from notification bar. 
> Thanks didnt knew the correct translation

**Comment by thestinger** [comment] 2020-07-09 07:17
I think it's a hardware issue. I doubt they do anything more than limiting brightness to a different range of something like that.

**Comment by thestinger** [comment] 2020-07-09 08:01
> It's not a hardware problem, and it's very easy to reproduce.

So it doesn't happen on the stock OS?

**Comment by crueltekk** [comment] 2020-07-09 08:02
Seems like it has something to do with the GammaCorrection.
https://www.xda-developers.com/custom-kernel-fix-green-tinting-issues-google-pixel-4-xl-units/

> So it doesn't happen on the stock OS?

Can test this in about an Hour when I'm home :)

**Comment by paintedman** [comment] 2020-07-09 08:13
In my case, this issue looks like when the image on the screen is being rendered, it has a greenish tint. And when the image is still, it has another tone.

I've tested this issue on AOSP, and it has flickering. On stock OS the screen works ok.

**Comment by crueltekk** [comment] 2020-07-09 08:36
On stock there seems to be no problem. Tested same settings as I have in Graphene but the greeny flicker does not appear.

**Comment by anupritaisno1** [comment] 2020-07-14 00:26
> It's not a hardware problem, and it's very easy to reproduce.
> 
> Set dark theme, go into a dark room, and turn down the brightness. Then try to use your phone, and you can notice that flickering.
> 
> > What do you mean by energy saving though?
> 
> I guess it's "Battery Saver" icon from notification bar.
> 
> I also have this flickering issue, and for me enabling this option helps too.

You're just describing pulse width modulation flickering. Which can cause the screen to look weird on camera and some people are more sensitive to it and notice the flickering

Also this is a hardware issue and something google has to solve. This is reproducible on the stock ROM for me on the pixel 4 and there's not a single user who hasn't had the issue from what I can tell

**Comment by paintedman** [comment] 2020-07-14 08:49
>You're just describing pulse width modulation flickering. Which can cause the screen to look weird on camera and some people are more sensitive to it and notice the flickering
Did you try what I wrote? It's not PWM. When the OS updates the screen, an image has a different greeny tint than in the stationary image.

Anyway, it's great that Google is going to fix this.

**Comment by thestinger** [comment] 2020-07-14 09:23
The only thing that GrapheneOS can / should do is match the configuration for refresh rate from the stock OS by making sure the resources are properly set up to match it if they aren't already. I don't think this issue is actionable as is unless it's determined that there is actually a different from the stock OS.

**Comment by thestinger** [comment] 2020-07-14 09:24
Just going to close this again. Submitting changes aligning resources with the stock OS is welcome. It may result in high refresh rate not being used at low brightness if there's configuration for that which they have set. I don't think an issue should be open about a hardware problem though.

**Closed by thestinger** 2020-07-14 09:24 UTC
Labels: bug, upstream
