### ISSUE TITLE
Pixel 3a - OSMAnd extremely slow map rendering on latest GrapheneOS

### ISSUE THREAD

**Issue by qubecub** [GrapheneOS/os_issue_tracker#171] opened 2020-01-28 12:56 UTC
Hi, 
I've recently flashed Google Pixel 3a (2019) with the latest release of GrapheneOS 
sargo-factory-2020.01.06.21.zip
The first app I tested on the new OS was OsmAnd maps. To my surprise map rendering was painfully slow, much slower than on older Samsung S7 phone (2016!). 
Zooming-in and zooming-out takes up between 5-10s just to respond and start drawing lines and shapes. I have to admit this comes as unexpected surprise. 

What log files can I check? How to check the log files? 

Please share your comments about the issue please. Has it already been raised by GrapheneOS users? 

I'm aware Pixel 3a is slightly slower than e.g. Pixel 3. But still it should be much faster than 2016 Samsung phone. In essence such slow map render makes Pixel 3a almost unusable for me.

**Comment by Finn10111** [comment] 2020-01-28 13:13
@qubecub I have the same phone with the same version of GrapheneOS running. I also use OsmAnd and the performance is fine I guess. Rendering is far away from real time but most of the time it takes about one or two seconds depending on the content to render. 

If I use it for navigation I don't see any negative effects.

**Comment by qubecub** [comment] 2020-01-28 13:38
@Finn10111 Thanks for such quick comment. 
Unfortunately my experience with OsmAnd shows it doesn't behave well on graphene and 3a. I've just had a side-by-side test of both phones and, especially with zooming-out, 3a can go up to 12s, whereas Galaxy S7 would finish rendering job within 3-4. (I chose a rather complex are of Tokyo for testing). 
There is also a difference in response - map on Pixel 3a seems to be drawn layer after layer and you can see it with 1/2s - 1s intervals. On S7 the map seems to get rendered much quicker and is shown as complete at once. 

Yesterday I did a couple of flashing cycles of 3a back to stock firmware and then again to graphene but I can't see any improvement in OsmAnd performance. 

Is it possible that some of the google / vendor specific drivers/sub-firmwares are missing in graphene? Is there any difference with regards to how google and graphene handle graphics? 

And lastly, is there anything I could check or explore to get to the source of this issue?

**Comment by beerisgood** [comment] 2020-01-28 17:51
Are you sure the problem is on our side?
Did you try Magic Earth? Doesn't have problems with that on my 3a

**Comment by qubecub** [comment] 2020-01-28 21:40
@beerisgood  - I have migrated to grapheneOS only couple of days ago and put it to a test with OsmAnd as it's probably most CPU heavy of the apps I use. Others are just communicators email, etc. which are definitely not going to be a problem. 
But the OsmAnd is slow. It might be OK for the less 'urbanized' areas, but for places like Tokyo, New York, Mexico, London, the amount of details just seem to throttle the CPU. 
I wonder if there would be much difference on Pixel 3. 
But back to my question - Is there any difference with regards to how google and grapheneOS handle graphics? Is it possible that some of the google/vendor specific drivers/ are missing in grapheneOS?
How can I get some logs on grapheneOS that would shed more light on what's going on behind the scenes?

**Comment by qubecub** [comment] 2020-01-28 21:41
@beerisgood  - I'm reluctant to use Magic Earth as it's proprietary app, something that contradicts the whole concept behind grapheneOS, I suppose.

**Comment by renlord** [comment] 2020-02-02 13:31
> Hi,
> I've recently flashed Google Pixel 3a (2019) with the latest release of GrapheneOS
> sargo-factory-2020.01.06.21.zip
> The first app I tested on the new OS was OsmAnd maps. To my surprise map rendering was painfully slow, much slower than on older Samsung S7 phone (2016!).
> Zooming-in and zooming-out takes up between 5-10s just to respond and start drawing lines and shapes. I have to admit this comes as unexpected surprise.
> 
> What log files can I check? How to check the log files?
> 
> Please share your comments about the issue please. Has it already been raised by GrapheneOS users?
> 
> I'm aware Pixel 3a is slightly slower than e.g. Pixel 3. But still it should be much faster than 2016 Samsung phone. In essence such slow map render makes Pixel 3a almost unusable for me.

This does not sound like a problem related to Graphene OS.
It being slightly slower is possibly caused by exec-spawn and hardened malloc performance tradeoffs.

To check logs, use `adb logcat`.

I suggest closing this issue since it has nothing to do with Graphene OS.

**Comment by thestinger** [comment] 2020-02-07 22:44
There's no indication that this has anything to do with a missing driver or anything like that. It could just be that OSMAnd is very poorly optimized and heavily bottlenecked by malloc throughput in a way that's highly impacted by the very hardened approach to memory allocation.

The thread is also not clear about how the performance compares to the stock OS.

If someone wants to work on diagnosing / measuring performance issues and improving performance, that's great, but I won't leave open very generic and non-actionable issues about it like this. It doesn't appear that there is any bug involved here.

**Closed by thestinger** 2020-02-07 22:44 UTC
Labels: upstream
