### ISSUE TITLE
Pixel 3A - alarms no longer working before the first unlock In 2020.11.03.03

### ISSUE THREAD

**Issue by ilikenwf** [GrapheneOS/os_issue_tracker#384] opened 2020-11-04 14:33 UTC
My dogs woke me up and saved me in terms of making it to work on time, however the alarms system app no longer work/go off. Is this a permissions thing or does a rebuild have to happen?

Either way I already tried clearing storage/cache for the app and the issue persists.

**Comment by i90faytn3** [comment] 2020-11-04 16:19
I confirmed this bug is present provided the alarm will trigger before it is first unlocked. 

Alarm is triggered after first unlock, then relocking it, as tested several times after this update (by setting alarm 1-2 minutes prior to rebooting, and on later tests, is by unlocking, setting an alarm 1 minute later then relocking the phone).

It seems like the alarm does not trigger before first unlock for some reason (which is quite buggy in the first place in DeskClock, as confirmed by other users, where the user-set alarm sound is not respected and playing some default sound regardless).

**Comment by thestinger** [comment] 2020-11-04 18:21
Is this only an issue before the first unlock, i.e. before your profile is decrypted? That would only mean that the Direct Boot feature isn't working, which is a relatively minor issue. Most clock apps don't have Direct Boot support.

**Comment by thestinger** [comment] 2020-11-04 19:46
I really need to know if this occurs after the initial unlock.

**Comment by charlesctr** [comment] 2020-11-04 20:39
I have tested on 4a and 3a XL on RP1A.201105.002.2020.11.03.03

Can confirm that : 
- On both the alarm doesn't ring if you don't unlock the phone for the first time just after a reboot.

- On both, after the first unlock the alarm clock is working normally.

**Comment by thestinger** [comment] 2020-11-04 20:47
Okay, so it's an issue specific to Direct Boot support.

**Comment by thestinger** [comment] 2020-11-04 20:49
I've adjusted the title to be about alarms no longer working before the first unlock. However, it's not entirely clear to me that this worked before 2020.11.03.03. Can anyone confirm that Direct Boot support (working before a profile is logged in) worked in the Clock app worked before 2020.11.03.03?

**Comment by beerisgood** [comment] 2020-11-04 21:17
> I've adjusted the title to be about alarms no longer working before the first unlock. However, it's not entirely clear to me that this worked before 2020.11.03.03. Can anyone confirm that Direct Boot support (working before a profile is logged in) worked in the Clock app worked before 2020.11.03.03?

i test my 3a with build 2020.10.23.04 and alarm works before first unlock (i only unlock SIM).

**Comment by thestinger** [comment] 2020-11-04 21:25
@beerisgood Is it broken with 2020.11.03.03 for you?

**Comment by beerisgood** [comment] 2020-11-04 21:26
> @beerisgood Is it broken with 2020.11.03.03 for you?

I will report tomorrow if i get the update (i'm on stable branch)

**Comment by beerisgood** [comment] 2020-11-05 16:55
> @beerisgood Is it broken with 2020.11.03.03 for you?

It's not broken with new update.
Setting alarm, shutdown phone, start phone, alarm is directly visible on locked display (I only unlock Sim) and alarm works with sound.
Same also with update before.

So I can't confirm this bug

**Comment by charlesctr** [comment] 2020-11-05 17:00
Hum, I made other test and here are the results :

 - When setting an alarm and doing a reboot between the time set and NOT doing the first unlock -> Alarm not ringing
 - When setting an  alarm and doing a reboot between the time set and doing the first unlock -> Alarm not ringing
 - When setting 2 or more alarms and doing a reboot between the time set and doing the first unlock : 
 1) First alarm not ringing
And here is the interesting part, if you open the clock app, all the following alarm set will ring.

**Comment by beerisgood** [comment] 2020-11-05 17:13
> Hum, I made other tests and here are the results :
> 
> * When setting an alarm and doing a reboot between the time set and NOT doing the first unlock -> Alarm not ringing
> * When setting an  alarm and doing a reboot between the time set and doing the first unlock -> Alarm not ringing
> * When setting 2 or more alarms and doing a reboot between the time set and doing the first unlock :
>   First alarm not ringing
>   And here is the interesting part, if you open the clock app, all the following alarm set will ring (at their specified time).

Maybe that's the difference here. You reboot while i fully shutdown and start the phone.

**Comment by charlesctr** [comment] 2020-11-05 17:28
> 
> 
> > Hum, I made other tests and here are the results :
> > 
> > * When setting an alarm and doing a reboot between the time set and NOT doing the first unlock -> Alarm not ringing
> > * When setting an  alarm and doing a reboot between the time set and doing the first unlock -> Alarm not ringing
> > * When setting 2 or more alarms and doing a reboot between the time set and doing the first unlock :
> >   First alarm not ringing
> >   And here is the interesting part, if you open the clock app, all the following alarm set will ring (at their specified time).
> 
> Maybe that's the difference here. You reboot while i fully shutdown and start the phone.

I tried the same tests with a manual shutdown/start and the results are the same of 3a xl and 4a.

**Comment by thestinger** [comment] 2020-11-05 17:35
Please test rebooting and logging in without manually launching the clock app. Do the alarms still work in that case?

**Comment by charlesctr** [comment] 2020-11-05 17:48
> 
> 
> Please test rebooting and logging in without manually launching the clock app. Do the alarms still work in that case?

No, the alarm does not work in that case (tested on 3a XL and 4a).

**Comment by thestinger** [comment] 2020-11-05 17:51
Getting inconsistent reports so it's not clear what's going on. Going to need each person to redo their tests and provide a very clear description of exactly what they've done to test it and trigger the problem.

**Comment by thestinger** [comment] 2020-11-05 17:51
Having it spread across multiple comments is too hard to untangle.

**Comment by thestinger** [comment] 2020-11-05 18:13
This has been addressed by giving it a battery optimization exemption by default. Please try doing that for the app manually.

**Comment by thestinger** [comment] 2020-11-05 18:13
Going to be working on a new release with this change.

**Closed by thestinger** 2020-11-05 18:13 UTC
Labels: bug, upstream

**Comment by beerisgood** [comment] 2020-11-05 18:31
> This has been addressed by giving it a battery optimization exemption by default. Please try doing that for the app manually.

Ah this is surely why it works for me but not for charlesctr as i disable battery optimisation in past (before this update)
