### ISSUE TITLE
2-button navigation option missing despite being the default gesture

### ISSUE THREAD

**Issue by inthewaves** [GrapheneOS/os_issue_tracker#336] opened 2020-09-27 03:18 UTC
Picture says it all: Using 2-button navigation but the option isn't there

<img width="45%" src="https://user-images.githubusercontent.com/26474149/94355030-4670db00-0035-11eb-87fa-ec19b353be0b.png">

**Comment by Bungeetaco** [comment] 2020-09-27 06:25
Same thing here, upgraded from Android 10 on Pixel 3 XL, and already had 2-button nav enabled prior to the upgrade to Android 11. The 2-button nav mode is still active on my phone, but the option can no longer be selected in the system navigation screen, thus if an user changes their navigation mode by mistake, it seems they wouldn't be able to go back to 2-button nav from the system settings interface directly.

**Comment by thestinger** [comment] 2020-09-27 15:03
I'm guessing the issue is caused bu missing overlay packages or interactions between overlays and exec spawning. We might just need to build / include this overlay package.

Look in `packages/apps/Settings/src/com/android/settings/gestures/SystemNavigationGestureSettings.java`.

**Comment by thestinger** [comment] 2020-09-27 21:39
Probably fixed by https://github.com/GrapheneOS/platform_frameworks_base/commit/f8774ab5b561de9960356c6e7601fae44864c2a2.

**Comment by thestinger** [comment] 2020-09-27 23:44
Confirmed that this is fixed.

**Closed by thestinger** 2020-09-27 23:44 UTC
Labels: bug, upstream
