### ISSUE TITLE
Properly support other languages than English in keyboard

### ISSUE THREAD

**Issue by laszlovl** [GrapheneOS/os_issue_tracker#247] opened 2020-07-22 13:17 UTC
Looks like the GrapheneOS keyboard only properly supports English language. A lot more languages are available to enable in the "Languages" setting for the GrapheneOS "Virtual keyboard", but once enabled it turns out spell check doesn't work properly.

For example, using the Spanish language will suggest Spanish words as autocomplete, but if you actually type a Spanish word it'll get a red underline and clicking it will suggest English words as correction instead.

Using the Dutch language won't provide you with any suggestions at all (even though a dictionary for NL is here: https://github.com/GrapheneOS/platform_packages_inputmethods_LatinIME/tree/10/dictionaries), but clicking a red underlined Dutch word will again suggest English words as correction.

Latest GrapheneOS on a Pixel 3a.

**Comment by thestinger** [comment] 2020-07-22 16:47
We don't develop the keyboard app. It's from AOSP.

**Comment by thestinger** [comment] 2020-10-05 01:10
Can you check if this is still an issue on Android 11? Probably, but just check to make sure.

**Comment by thestinger** [comment] 2020-10-05 01:12
Are you sure you're changing the spell checker language? It's a separate setting. I think that's the issue. Going to close this since that seems to be the problem.

**Closed by thestinger** 2020-10-05 01:12 UTC
Labels: bug, upstream

**Comment by laszlovl** [comment] 2020-10-05 07:51
Upgraded to the latest GrapheneOS just now, and the problem persists.

I go to system -> languages & input -> grapheneos keyboard -> languages to enable additional languages next to English, e.g. Spanish and Dutch. The keyboard then lets me toggle between those 3 languages.

**Comment by thestinger** [comment] 2020-10-05 07:57
Spell check is a separate option.

**Comment by thestinger** [comment] 2020-10-05 07:58
System -> Languages & input -> Spell checker

**Comment by thestinger** [comment] 2020-10-05 07:59
You probably shouldn't configure either of those things directly. Why aren't you just adding the languages as system languages via Languages & input -> Languages? It's strange to be configuring them specifically for the keyboard or spell checker.

**Comment by laszlovl** [comment] 2020-10-05 08:09
Ha, thanks for the pointer. Pretty sure I always did it like this on previous Android versions and that worked OK.

Adding Spanish as system language gives me properly working spellcheck!

However, it's still broken for Dutch. In the spell checker settings, I can only choose for English, French, German, Italian, Spanish, Russian and Portuguese. Any thoughts on that?

**Comment by laszlovl** [comment] 2020-10-07 10:50
@thestinger Consider re-opening this ticket for the remaining issue?

**Comment by thestinger** [comment] 2020-10-07 10:54
Can you open a new issue for that? It might just not be expected to support more than those languages though. We don't actively develop the keyboard so unless there's something broken for us to fix we're unlikely to do much. It's the AOSP keyboard with minor privacy enhancements from us. I'd recommend looking at other open source keyboards as alternatives. We could potentially replace it with a permissively licensed one.

**Comment by laszlovl** [comment] 2020-10-07 11:15
OK, created a separate issue at #358. I've tried AnySoftKeyboard and the other keyboards available at f-droid, but they're pretty bulky/ugly to my taste compared to the plain and simple AOSP keyboard. Would be great if these additional languages could be made available in the spell checker, perhaps it's just a simple configuration option somewhere. :-)

**Comment by gsture** [comment] 2022-03-28 15:54
This is still an issue. Changed spell check and keyboard dictionaries to dutch. There is no spell check and no autocomplete.

**Comment by thestinger** [comment] 2022-03-28 15:59
Okay, then perhaps we need to roll back the addition of Czech and Dutch if it wasn't done in a complete way.

**Comment by gsture** [comment] 2022-03-28 16:09
I updated to latest beta and tried everything  to get it to work but the fix does not seem to work correctly, at least not in my situation. 

Things I tried:

- Set keyboard language to Dutch and installed dutch dictionary
- Set spell check language to dutch
- Tried switching system language from English to Dutch so I could try "use system language" option. 
- Disabled/removed all other installed dictionaries
- Cleared keyboard data and cache. 

Dutch spell check and keyboard text prediction is not working as it should. Not in main and not in work profile.

**Comment by edd-2** [comment] 2023-01-05 10:11
I have the same problem with the Dutch spellcheck. I tried the same things @gsture tried without succes.

**Comment by thestinger** [comment] 2023-01-05 10:14
Use a different keyboard.

**Comment by pepijndevos** [comment] 2023-10-16 14:53
My previous LineageOS phone was using the AOSP keyboard and worked fine with Dutch, but with GrapheneOS the spell checker freaks out, despite being set to "system languages" which include Dutch. So I would suspect there has been either a regression since Android 12, or it's actually a GrapheneOS bug.

That said, did any of you find a good alternative keyboard?

**Comment by thestinger** [comment] 2023-10-16 15:02
LineageOS isn't based on Android 14. Android 14 regressed how the AOSP keyboard handles multiple languages since it depended on something undefined before. Also, we don't add more languages as supported.

**Comment by thestinger** [comment] 2023-10-16 15:02
There are lots of other keyboards, both open source and proprietary ones. Many people simply use Gboard.

**Comment by pepijndevos** [comment] 2023-10-16 15:51
Thanks. I can confirm that OpenBoard correctly handles multiple languages including Dutch. Hopefully the AOSP issue gets resolved at some point to provide a better out of the box experience, but I understand GrapheneOS focuses on security enhancements primarily.

**Comment by san-alt-delete** [comment] 2026-05-04 11:57
This should not be closed. This is still a problem with Dutch. Other ROMs do not seem to have this issue.

**Comment by thestinger** [comment] 2026-05-04 16:21
Not having a Dutch dictionary is a different thing from anything being broken. You can use a different keyboard. Also, GrapheneOS is not a ROM (read-only memory firmware).
