### ISSUE TITLE
Can't create configurable widgets on stock launcher / Launcher crash

### ISSUE THREAD

**Issue by genericusername87** [GrapheneOS/os_issue_tracker#4250] opened 2024-10-31 17:24 UTC
When adding a configurable widget (those with a pencil icon in the bottom right corner, which provides customization options) to the home screen, the launcher just adds an empty frame to the top left corner (regardless of the chosen position):

![ResizedImage_2024-10-31_17-07-45_0.png](https://github.com/user-attachments/assets/6ce6bd5f-7d08-4cd7-bcae-36189912f097)

When tapping either inside or or outside the frame, the widget/frame instantly disappears.
Tapping on the pencil icon causes a crash of com.android.launcher3:

```
type: crash
osVersion: google/shiba/shiba:15/AP3A.241005.015/2024102400:user/release-keys
package: com.android.launcher3:35
process: com.android.launcher3
processUptime: 21085 + 254 ms

java.lang.IllegalArgumentException: Bad widget id 29
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3255)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.createAppWidgetConfigIntentSender(IAppWidgetService.java:910)
	at android.appwidget.AppWidgetHost.startAppWidgetConfigureActivityForResult(AppWidgetHost.java:333)
	at com.android.launcher3.widget.LauncherWidgetHolder.startConfigActivity(LauncherWidgetHolder.java:220)
	at com.android.launcher3.AppWidgetResizeFrame.lambda$setupForWidget$3(AppWidgetResizeFrame.java:281)
	at com.android.launcher3.AppWidgetResizeFrame.$r8$lambda$XfAwILfqEwKawq7oyWCzz9aqDeA(Unknown Source:0)
	at com.android.launcher3.AppWidgetResizeFrame$$ExternalSyntheticLambda5.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:8028)
	at android.view.View.performClickInternal(View.java:8005)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31229)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl.createAppWidgetConfigIntentSender(AppWidgetServiceImpl.java:1220)
	at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:431)
	at android.os.Binder.execTransactInternal(Binder.java:1529)
	at android.os.Binder.execTransact(Binder.java:1468)
```

I have cross checked this with 3 different apps (Aves Gallery, Breezy Weather and Poweramp, all targetSdk 34) and it was always reproducible. I have also tried it after clearing the storage of com.android.launcher3 but that brought no change.
Also tested with an third party launcher (Lawnchair 14 Beta 3), where it worked fine.

"Normal" widgets (without the pencil icon) seem unaffected and can be created, repositioned and resized.

I first recognized this behavior in release 2024102100. So I guess this is an newly introduced (upstream) bug with Android 15.

**Comment by splattergamesextended** [comment] 2024-10-31 23:08
> Also tested with an third party launcher (Lawnchair 14 Beta 3), where it worked fine.

Very interesting, it's the opposite for me. I can configure customizable widgets in Launcher3, but they fail to create in Lawnchair if that one is set as default. Started to happen after Android 15 for me while other users had that bug way earlier (referenced in [this](https://github.com/LawnchairLauncher/lawnchair/issues/4856) Github issue). I wonder if this is really related to the launcher itself or something in the OS.

**Comment by empratyush** [comment] 2024-11-04 03:20
[unable to reproduce this](https://github.com/GrapheneOS/os-issue-tracker/issues/4275#issuecomment-2453756827), closing in favour of #4275.

**Closed as not planned by empratyush** 2024-11-04 03:20 UTC
Labels: bug, upstream
