### ISSUE TITLE
MindBody Business App Hangs

### ISSUE THREAD

**Issue by liberateyourtech** [GrapheneOS/os_issue_tracker#251] opened 2020-07-26 11:01 UTC
App name: Business
ID: com.mindbodyonline.express
Version: 6.1.0
Source: Aurora Store

Latest Graphene OS for Pixel 2

I have tested this app on other devices (Lineage no microG) and works fine
Tried uninstall and reinstall

App installs fine and user account setup completes fine
Hangs immediately after launching every time
App looks ok but completely unresponsive
Within a few seconds the entire screen is unresponsive
Eventually the 'App unresponsive' dialogue opens and i force close

Emailing a bug report zip now

Hope you can help!

Many thanks!

**Comment by liberateyourtech** [comment] 2020-07-27 09:45
Tested with older versions of this app (Mindbody Business)

No versions from 5.10.0 onwards are working

Previous versions are working

Will send app devs feedback

I realise this is low priority but if you find anything I will send it on to the app devs

Many thanks!

**Comment by thestinger** [comment] 2020-07-27 19:28
Make sure to mention that GrapheneOS doesn't have Play Services. The issue is probably that they depend on Play Services and don't provide a proper fallback, even though baseline Android doesn't include Play Services.

**Comment by anupritaisno1** [comment] 2020-07-31 01:24
Cannot reproduce here. Got a log?

**Comment by anupritaisno1** [comment] 2020-08-07 03:56
@liberateyourtech we recently fixed an sepolicy issue that caused certain apps to crash. Please upgrade to that build once it is out and test if the crash still occurs

**Comment by thestinger** [comment] 2020-10-04 23:34
Need an update on whether this is still a problem and more information about it. Going to close it for the time being.

**Closed** 2020-10-04 23:34 UTC
Labels: bug, upstream
