### ISSUE TITLE
Pixel4a camera not being able to take more than 1 photo

### ISSUE THREAD

**Issue by Randomdude8192** [GrapheneOS/os_issue_tracker#444] opened 2021-02-09 11:32 UTC
So on my Pixel4a this problem has been there for about a month. I am able to take 1 photo and than I have to reboot device to be able to take more. It does the same crap on Signal's camera feature.

**Comment by thestinger** [comment] 2021-02-09 18:33
Looks like a duplicate of https://github.com/GrapheneOS/os_issue_tracker/issues/385. Please turn off the HDR toggle you enabled. It doesn't work properly yet.

**Closed by thestinger** 2021-02-09 18:33 UTC
Labels: Pixel 4a, bug, upstream
