### ISSUE TITLE
MAC randomization doesn't appear like it changes in Saved networks

### ISSUE THREAD

**Issue by ineshi2** [GrapheneOS/os_issue_tracker#165] opened 2020-01-08 03:54 UTC
1. Go to settings -> Wi-Fi -> Saved networks
2. Select any saved network
3. Change the Privacy/MAC settings to something else
4. Press the back button once
5. Go back to that same saved network
6. See that the MAC randomization setting looks like it didn't change from before

But if you do step 4 two times (back, back, saved networks, then go back to the same network), the change will have applied

**Comment by ineshi2** [comment] 2020-01-08 03:57
This is for QQ1A.200105.002.2020.01.06.21

**Comment by thestinger** [comment] 2020-01-08 04:01
cc @renlord

**Comment by dallemon** [comment] 2020-01-08 12:25
Just to confirm that it works if you press back twice (exiting "saved networks") after changing the privacy settings.
Tested for currently connected network and other saved networks.

**Comment by renlord** [comment] 2020-01-09 09:35
@thestinger please add upstream tag, it is also a problem on stock android `sargo-qq1a.200105.002`

**Comment by renlord** [comment] 2020-01-09 09:41
at the mean time, please just double-tap back so the preferences (i.e. wifi network tabs) are refreshed.

**Comment by beerisgood** [comment] 2020-01-09 18:00
I try all solutions here but can't get my original MAC for my wifi. The systeminfo under "about" list the real one but even if a create new wifi connection, i doesn't get the real one.

Only a random MAC which doesn't change after use the workaround. Anyone can confirm?

**Comment by renlord** [comment] 2020-01-09 23:06
> I try all solutions here but can't get my original MAC for my wifi. The systeminfo under "about" list the real one but even if a create new wifi connection, i doesn't get the real one.
> 
> Only a random MAC which doesn't change after use the workaround. Anyone can confirm?

Can you please rephrase what you are trying to accomplish?

If you want to re-connect to the Wi-Fi network with your Device MAC, please just select "use Device MAC" option in the Wi-Fi Privacy Settings.

**Comment by beerisgood** [comment] 2020-01-10 07:50
@renlord after the new update I can't update to my wifi (which use profiles based on MAC). The problem was that my device send a new MAC.

I then see that randomization was enabled, even if I disable that in the past.

And any try to send the real MAC wasn't successful. Even if I config that my real MAC should be send it doesn't work. The only thing what works is that a random MAC is generated and it doesn't change to another random but that's not equal to the real device MAC

**Comment by thestinger** [comment] 2020-01-10 08:07
Did you do this? You didn't give a response to what @renlord wrote.

> If you want to re-connect to the Wi-Fi network with your Device MAC, please just select "use Device MAC" option in the Wi-Fi Privacy Settings.

The most recent update did NOT introduce MAC randomization, only an alternative way of doing it. It seems to be working exactly as intended for you.

**Comment by beerisgood** [comment] 2020-01-10 09:02
> 
> 
> Did you do this? You didn't give a response to what @renlord wrote.
> 
> > If you want to re-connect to the Wi-Fi network with your Device MAC, please just select "use Device MAC" option in the Wi-Fi Privacy Settings.
> 
I do and it doesn't work as it does before the new update

**Comment by thestinger** [comment] 2020-01-10 09:49
Can you file a new issue then? Doesn't seem related.

**Comment by beerisgood** [comment] 2020-01-10 12:17
> 
> 
> Can you file a new issue then? Doesn't seem related.

Sure. [Done](https://github.com/GrapheneOS/os_issue_tracker/issues/167)

**Comment by thestinger** [comment] 2020-03-04 14:25
This should be resolved by the upstream changes. The always-on MAC randomization feature is not currently working properly and behaves like the persistent randomization option but that's a separate problem.

**Closed by thestinger** 2020-03-04 14:25 UTC
Labels: bug, upstream
