### ISSUE TITLE
Losing notification sounds

### ISSUE THREAD

**Issue by raccoonia** [GrapheneOS/os_issue_tracker#208] opened 2020-04-25 07:24 UTC
This issue is identical to #143 

On a new install of a Pixel 3a, I have had the notification sounds revert back to a default sound just as described in #143 . After a reboot the system sees all ringtones, after some time (random) and several phone calls later I notice my ringtone changes to the default one. When this happens, the notification sound list contains only numbers no sound names.
A reboot fixes the issue only temporarily.

FIX:
I have not had this issue for a few days now after I did the following:
I cleared the storage and cache of Media Storage and forced a stop. I rebooted the device and for a few days now this issue has not reoccurred.

Thank you!

**Comment by renlord** [comment] 2020-04-29 08:21
I sometimes have this issue also but can never really get the logs reliably to see what causes this to happen.

**Comment by eenbroleke** [comment] 2020-05-14 10:03
I'm having the same issue as @raccoonia (no notification sound, no ringtone sound).
If trying to select another ringtone/notification, the list is empty-like: only "None" and what I guess is a numerical ID of the previously selected item is displayed.

I'll try what raccoonia did and report back in case the issue happens again.
Note that I was running the last version (may 2020) of GrapheneOS on a sargo device, with a an installation done from scratch (no update).

**Comment by eenbroleke** [comment] 2020-05-17 21:49
Unfortunately, the issue is still there. It reappears randomly over time.

**Comment by wow20** [comment] 2020-05-29 22:37
I'm having this issue to I have the latest version once in awhile I will have to restart my phone to fix it I have a Google pixel 3 XL

**Comment by eenbroleke** [comment] 2020-06-05 17:09
`06-05 19:07:45.794 11004 11272 D Ringtone: Successfully created local player
06-05 19:07:45.794 11004 11272 W Ringtone: Use of stream types is deprecated for operations other than volume control
06-05 19:07:45.794 11004 11272 W Ringtone: See the documentation of setStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-05 19:07:45.794  1108  2963 I Codec2Client: Client to Codec2 service "software" created
06-05 19:07:45.794  1108  1108 D NuPlayerDriver: reset(0xee34ad00) at state 4
06-05 19:07:45.794  1108  2963 I Codec2Client: Creating a Codec2 client to service "default"
06-05 19:07:45.794  1108 20864 I Codec2Client: Creating a Codec2 client to service "default"
06-05 19:07:45.795  9593 10406 W MediaProvider: Trouble resolving content://media/internal/audio/media/99; falling back to search: java.io.FileNotFoundException: No item at content://media/internal/audio/media/99
06-05 19:07:45.795  1108 11274 D NuPlayerDriver: notifyResetComplete(0xee34ad00)
06-05 19:07:45.796  1108  1108 D NuPlayerDriver: reset(0xee34ad00) at state 0
06-05 19:07:45.796  9593  9637 W MediaProvider: Trouble resolving content://media/internal/audio/media/221; falling back to search: java.io.FileNotFoundException: No item at content://media/internal/audio/media/221
`

**Comment by eenbroleke** [comment] 2020-06-15 16:16
@thestinger 
Hi, how can we contribute to this issue ?

**Comment by thestinger** [comment] 2020-10-04 23:33
I don't think this is a problem anymore. Let me know if it still occurs.

**Closed by thestinger** 2020-10-04 23:33 UTC
Labels: bug, status-unconfirmed, upstream

**Comment by privateseabass** [comment] 2020-10-07 17:43
It is occuring for me.
Just did a factory reset and even reinstalled grapheneOS.
When I try the fix mentioned  at the start of this issue, I don't get the option to clear cache/storage, so I couldn't do it anyway.
Even after restarting the phone I didn't get sound for ringtones and alarms.
