### ISSUE TITLE
Proximity sensor that turns off the screen [3a XL/Bonito]

### ISSUE THREAD

**Issue by charlesctr** [GrapheneOS/os_issue_tracker#360] opened 2020-10-08 18:43 UTC
Hello,

I am on the beta RP1A.201005.004.2020.10.06.02

The issue has been fixed with a reboot but I submit it anyway (if someone runs into it).
When the proximity sensor detects something (my hand, a table or whatever) the screen would immediately turn off. Phone is not locked, just the screen being turned off.
Like when you are in a phone call, it's exactly the same except you are not.

I don't know if it's a thing with Android 11 or only the 3a/3a XL.
Couldn't get log when I had the issue, but if it happends again I will catch them.

**Comment by thestinger** [comment] 2020-10-08 20:42
Did this start happening after a phone call? It seems possible that the dialer app was still running and somehow didn't toggle off this feature. You might have been able to resolve it by killing the dialer app. I don't think we're going to be able to do much about this aside from keeping an eye out for a fix for this issue in AOSP master. However, I think it's going to be difficult to backport fixes for apps from master this year due to migration to Kotlin.

**Comment by charlesctr** [comment] 2020-10-08 21:01
Yes, I made a phone call 15 minutes before this happened.
As you said it's an issue from the dialer app from AOSP.

Should I submit an issue there ?

**Comment by thestinger** [comment] 2020-10-08 21:10
Is it possible that it was happening for that entire 15 minutes and it just took a while to notice? I'd guess that the Dialer just never told the OS that the call ended.

**Comment by charlesctr** [comment] 2020-10-08 21:23
No I didn't notice it immediately there was no UI glitch until I see the screen turns off for no reason.
I wanted to submit the issue if other people have it in the future.
We know it's not related to Graphene but the AOSP's dialer.

**Comment by thestinger** [comment] 2020-10-08 21:25
I mean that it might have started happening immediately after the call but you didn't trigger the sensor until later, or didn't notice it right away.

**Comment by anupritaisno1** [comment] 2020-10-10 17:35
Couldn't reproduce on pixel 4

**Comment by thestinger** [comment] 2020-10-10 19:54
I don't think we'll be able to do much about this. As I said above, it's likely a Dialer issue, and could be abug in it where it didn't end up disabling this after the call ended. We'll keep an eye out for a fix from upstream.

**Closed by thestinger** 2020-10-10 19:54 UTC
Labels: bug, upstream
