### ISSUE TITLE
Deleting too many files at once in the "Files" app fails

### ISSUE THREAD

**Issue by dspacejs** [GrapheneOS/os_issue_tracker#351] opened 2020-10-03 12:28 UTC
I was deleting a bunch of recursive folders, with lots of files in each folder. It also took up a lot of space.

I could only delete a few folders at a time, otherwise it failed. I had to manually go through the directory and delete only a few folders at a time.

**Comment by thestinger** [comment] 2020-10-04 20:44
Is this happening with the system file manager?

**Comment by dspacejs** [comment] 2020-10-06 03:17
@thestinger yep

**Comment by thestinger** [comment] 2020-10-30 10:46
Can you try this again on the current release?

**Comment by charlesctr** [comment] 2020-10-30 15:55
@thestinger Had this issue too, but with RP1A.201005.004 (Pixel 3aXL/Bonito) on beta it is fixed. Folders with a big numbers of files in it can be deleted without issue. 
For me the current release fixed this issue and I can't reproduce the bug.

**Comment by thestinger** [comment] 2020-10-30 16:11
Okay, it seems like this was likely fixed by that first round of upstream Android 11 fixes for the October patch. If this is still an issue, please file a new issue giving the OS version, impacted device and also output from adb logcat.

You can run `adb logcat -c` to clear the logs, then replicate the issue, then do `adb logcat -d > files.log` to get all of the logs from the OS since clearing it. You can then open up that file and delete unnecessary context from above and below the relevant logs but try to include as much as possible.

Just review it to make sure there isn't private information. You could also send the log to us privately but it's nice to have it available publicly. You can use a Markdown code block to format it nicely.

**Closed** 2020-11-04 20:26 UTC
Labels: bug, upstream
