### ISSUE TITLE
Alarms from clock app cannot be dismissed without unlocking

### ISSUE THREAD

**Issue by FWDekker** [GrapheneOS/os_issue_tracker#350] opened 2020-10-03 06:08 UTC
## Context
Previous issues such as #218 and #335 mention the clock app stopping to work. My issue is different because the clock app does not stop working.

## Issue description
Alarms cannot be dismissed or snoozed from the lock screen. When an alarm goes off, the phone vibrates and makes sound, but does not display anything related to the alarm in the lock screen. After unlocking the phone, the alarm can be dismissed after manually opening the notification tray or from the clock app itself. This is inconvenient because I usually don't unlock my phone in one try right after waking up.

This issue has started occurring since the update to Android 11.

Rebooting does not resolve my issue.

## Build information
|||
| --- | --- |
| Device | Pixel 2 |
| OS | Android 11 |
| Build | RP1A.200720.009.2020.09.29.20 |

**Comment by thestinger** [comment] 2020-10-03 06:16
You should be able to tap the notification on the lockscreen. This is a known upstream change in the clock app in Android 11. It had substantial changes and has far more substantial changes in the master branch. We have the option of switching to the newer version that's in development.

**Comment by anupritaisno1** [comment] 2020-10-03 10:01
@thestinger this is apparently an issue many people on stock are complaining about. I just skimmed through a few pixel chats and looks like this is widespread

**Comment by beerisgood** [comment] 2020-10-03 14:42
Confirm this on my 3a.

Also the alarm activates itself 30 minutes before alarm should make sound. This is always reproducible

**Comment by thestinger** [comment] 2020-10-03 19:22
It doesn't activate itself early but rather the notification is configured to generate a sound when it appears. You can disable that.

**Comment by beerisgood** [comment] 2020-10-03 19:47
> It doesn't activate itself early but rather the notification is configured to generate a sound when it appears. You can disable that.

Yeah this is what i mean.
So i disable it already in the right way?

**Comment by thestinger** [comment] 2020-10-03 19:48
Yes, if that's the right notification channel.

**Comment by thestinger** [comment] 2020-10-03 19:49
You should configure the notification channel to disable sound. Don't outright disable the notification channel or you won't get the notification anymore. You might want to clear the app data to get rid of any legacy notification channels.

**Comment by beerisgood** [comment] 2020-10-03 20:31
> You should configure the notification channel to disable sound.

How can i do that?
I also clear app data which fix the double/ old notification channels. After cleaning the app data and re-open the app, i get the popup may not be designed for this Android version. Wasn't this fixed before ?

**Comment by thestinger** [comment] 2020-10-03 20:35
> i get the popup may not be designed for this Android version. Wasn't this fixed before ?

No, it's updated to API 25 now, and we show a warning for 28+.

**Comment by thestinger** [comment] 2020-10-03 20:35
In the master branch of AOSP it's rewritten as a modern Kotlin app. We could try switching to that but it might have problems.

**Comment by thestinger** [comment] 2020-10-05 04:51
This should be addressed for the next release. You can let me know if it's still a problem after the update and this can be reopened.

**Comment by beerisgood** [comment] 2020-10-05 05:37
Okay!

**Comment by FWDekker** [comment] 2020-10-05 10:05
Thanks! Will do!

**Comment by beerisgood** [comment] 2020-10-07 17:36
I sadly doesn't see any change

**Comment by sk425** [comment] 2020-10-18 01:47
_since updating to RP1A.201005.004.2020.10.06.02 on  pixel 3xl_

Current issues:

- Alarm/timer cannot be dismissed without unlocking the phone when other notifications on the lock screen push it to the bottom removing the ability to open it independently

Issues resolved after updating and clearing app data:

- Notification sound from "upcoming alarm" notification resolved by turning notification sound to "none" rather than setting the notification profile to "silent"

- Dismissing alarm/timer from lock screen by tapping it  (sometimes repeatedly until it opens) when its visible as an independent notification block

_Please note: I have battery optimizations turned off on the app. This seems to have improved alarm reliability in the past._

**Comment by nigle-dev** [comment] 2020-10-18 09:24
I can easily hit the turn off button or snooze button if this is the only notification block. But with multiple notification blocks, even if alarm is the top one it's very hard to dismiss. You can see the button is there underneath the arrow but in most cases trying to hit it it pops up the unlock screen.
This is on a Pixel 3a, after clearing app data and on RP1A.201005.004.2020.10.06.02

**Comment by i90faytn3** [comment] 2020-11-04 16:21
Not reproducible in the latest update, can drag down and then press dismiss/pause/reset quickly before the alarm time or timer counts down to zero.

Alarms and timers can be now dismissed when triggered in the lockscreen, after first unlock.

**Closed** 2020-11-04 18:19 UTC
Labels: bug, upstream

**Comment by FWDekker** [comment] 2020-11-09 13:18
As of the latest update the old overlay once again appears where you can easily dismiss/snooze the alarm, so for me the issue is now completely resolved! :)

**Comment by beerisgood** [comment] 2020-11-09 16:24
> As of the latest update the old overlay once again appears in the lock screen where you can easily dismiss/snooze the alarm, so for me the issue is now completely resolved! :)

can confirm this.
Works perfect now

**Comment by jgeerds** [comment] 2020-11-09 22:44
Yep, for me too
