### ISSUE TITLE
Pixel 4 and Pixel 4 XL don't have have always-on display enabled

### ISSUE THREAD

**Issue by krombopulosM** [GrapheneOS/os_issue_tracker#241] opened 2020-07-12 14:46 UTC
not sure if this is a bug or what, someone pointed out it may be due to the fact the pixel 4 doesn't have this feature built into AOSP but I thought I'd post here just to be safe.

On other pixel devices you can find the feature under Display > Advanced > Lock screen display > "when to show" always-on 
but for the Pixel 4 series I can't find that option at all.

**Comment by thestinger** [comment] 2020-07-12 14:52
Each device needs to have their resource configuration ported over properly from the stock OS. There are already other issues like https://github.com/GrapheneOS/os_issue_tracker/issues/238 and likely https://github.com/GrapheneOS/os_issue_tracker/issues/239 tied to the same thing. Device maintainers need to extract the resource overlays from the stock OS and port them to GrapheneOS.

**Comment by anupritaisno1** [comment] 2020-07-14 12:09
@krombopulosM I have no intention to support this especially on the pixel 4

@thestinger https://github.com/GlassROM-devices/device_google_coral/commit/c87639a050b44f599645b2e8729fe938c2b32925#diff-e0a3646285a5f4f89d0d2f1cd05c0458

**Comment by thestinger** [comment] 2020-07-14 12:31
Ah, it's also disabled on the stock OS?

Is it supposed to have some kind of proximity sensor enabled so it detect when you wave over it?

**Comment by thestinger** [comment] 2020-07-14 12:32
Also there might be a difference between *available* and *enabled*. We might be supposed to have an overlay making it *available* just not enabled by default.

**Comment by Flex1911** [comment] 2020-07-14 20:55
Exactly, the commit linked above only means that AOD disabled **by default**.
It's unavailable because in stock it works with aware (oslo/soli) mode that is not implemented in AOSP, even though it still checks aware prop to hide AOD from settings. You have to revert https://github.com/GrapheneOS/device_google_coral/commit/b73112b74bbac667e61f2aaf84e90a7f41863f52 to make it available.

**Comment by lpcvoid** [comment] 2020-10-06 08:08
Are there any regressions to be expected by simply reverting this commit? I would like to see this change incorporated since I would like to use AOD on my p4xl.

**Comment by Flex1911** [comment] 2020-10-06 10:44
> > Exactly, the commit linked above only means that AOD disabled **by default**.
> > It's unavailable because in stock it works with aware (oslo/soli) mode that is not implemented in AOSP, even though it still checks aware prop to hide AOD from settings. You have to revert [GrapheneOS/device_google_coral@b73112b](https://github.com/GrapheneOS/device_google_coral/commit/b73112b74bbac667e61f2aaf84e90a7f41863f52) to make it available.
> 
> Are there any regressions to be expected by simply reverting this commit? I would like to see this change incorporated since I would like to use AOD on my p4xl.

no, not really. Aware is only used with proprietary Google framework. It has no use in AOSP and is in fact only referenced in AOD code.

**Comment by lpcvoid** [comment] 2020-10-07 07:07
> > > Exactly, the commit linked above only means that AOD disabled **by default**.
> > > It's unavailable because in stock it works with aware (oslo/soli) mode that is not implemented in AOSP, even though it still checks aware prop to hide AOD from settings. You have to revert [GrapheneOS/device_google_coral@b73112b](https://github.com/GrapheneOS/device_google_coral/commit/b73112b74bbac667e61f2aaf84e90a7f41863f52) to make it available.
> > 
> > 
> > Are there any regressions to be expected by simply reverting this commit? I would like to see this change incorporated since I would like to use AOD on my p4xl.
> 
> no, not really. Aware is only used with proprietary Google framework. It has no use in AOSP and is in fact only referenced in AOD code.

Thanks, I think this can be closed now in that case.

**Comment by thestinger** [comment] 2020-10-07 07:46
This will be part of the next release.

**Closed** 2020-10-07 07:46 UTC
Labels: enhancement, upstream
