### ISSUE TITLE
Default spell checker marks words followed by a period as incorrectly spelled in app text fields

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/os_issue_tracker#758] opened 2021-10-26 21:32 UTC
![IMG_20211026_141018](https://user-images.githubusercontent.com/33134232/138961514-9934eed8-db49-4acf-826b-9f3b8390b69c.jpg)
Keyboard doesn't seem to matter. Tested with both AOSP keyboard and FlorisBoard.
Seems to only occur in app text fields with auto-correction for example, AOSP Messaging or Element.
The word with the period included can be added to the dictionary and it won't be marked as incorrect anymore.

**Comment by Ickwit** [comment] 2021-11-04 19:26
I have the same issue as well (Pixel 4a - 5G SP1A.210812.015.2021102613) but if I try to add it to the dictionary the word is still marked as mis-spelled.  I only use the GrapheneOS keyboard.

**Comment by ezeeman** [comment] 2021-11-07 20:19
This problem appeared just a few days ago for me while it was first reported here 12 days ago. I'm using OS version 2021102300 SP1A.210812.015.2021102300 on a Pixel 4a.

**Comment by nep2ner** [comment] 2021-11-10 10:29
I've been seeing this on Android 12 Pixel 5a too.

**Comment by JanOstrowka** [comment] 2021-11-11 21:43
I've had the same issue since Android 12

---

Specification:
os: 2021110617
phone: Pixel 5

**Comment by greenerk** [comment] 2021-12-08 06:50
Checking in, confirming the issue.
Still present with 2021112404 on Pixel 4a.

**Comment by thestinger** [comment] 2021-12-08 07:21
Not enough information is being provided such as the language and keyboard configuration.

**Comment by greenerk** [comment] 2021-12-08 11:05
Sorry about that.  In my particular case it's happening with *any* keyboard I use.  AnySoft, OpenBoard, the default one. Language is English GB.

I've personally tried removing all keyboards, resting/emptying dictionaries, all sorts.

My wife has the same phone and is seeing the same issue. Her device is completely "stock" GrapheneOS except for the Signal and DuckDuckGo browser apps.

Is there anything we can be doing to help resolve the issue?
My next stage was to completey reflash my device with GrapheneOS and start again. But I'd really rather not.

I'm assuming you're unable to reproduce it yourself?

**Comment by ezeeman** [comment] 2021-12-08 18:56
Build number: SP1A.211105.004,2021112404

From Settings | System | Languages & input:
- Languages: English (United States) 
- On-screen keyboard: GrapheneOS Keyboard
- Physical keyboard: Not connected
- Spell checker: GrapheneOS Spell Checker

**Comment by dailyherold** [comment] 2021-12-29 04:32
This happens for me as well on my Pixel 6, build *2021122018
- Language: English (US)
- On-screen keyboards: GrapheneOS Keyboard, and GBoard
- Spell checker: GrapheneOS Spell Checker

**Comment by greenerk** [comment] 2022-01-27 06:52
I may have found a fix!
I went to _Settings > System > Languages and Input > Spell Checker_ .
Under **Default Spell Checker** I selected a different option from one of the installed keyboards, tested typing, then selected the GrapheneOS Spell Checker again.

No more incorrect red underlines!

It looks like whatever is causing the problem becomes "unstuck" when changing the Spell Checker chosen.

Have a go and report back please.

**Comment by greenerk** [comment] 2022-01-27 06:56
Ah poo. I was premature in my excitement.
All other spell checkers are fine - once I tested a text box in another app the GrapheneOS Spell Checker still has the same problem.
If I select the Spell Checker of another keyboard the problem goes away.

So close.

**Comment by greenerk** [comment] 2022-01-27 07:07
So it appears to depend on the spell checker. I downloaded a few keyboards to test...

- GrapheneOS = incorrect red underlines with a manual period.
- OpenBoard = incorrect red underlines with a manual period.
- FlorisBoard = no underlines at all.  But I think this is a Floris thing.
- Gboard (_hey, I had to know_) = Works fine. Red underlines for spelling errors only.

I'd like to use the default GrapheneOS Spell Checker so will continue to poke about to see if my limited abilities can find something to get someone's teeth into.

**Comment by oldmanonthebus** [comment] 2022-01-28 01:43
I found that if you double space (2 X space key) at the end it auto adds
the period without the underline.  I don't know why this is.

**Comment by greenerk** [comment] 2022-01-28 06:23
This is standard for almost all keyboards with autocorrect now. They have an option for "auto punctuation" to add in a period when double tapping the space button.  Nothing to do with the bug this ticket is for.

![Screenshot_20220128-062027_1](https://user-images.githubusercontent.com/56622533/151497838-925e0a86-2a8b-4d03-97df-7f24132158d8.png)

**Comment by nep2ner** [comment] 2022-01-28 07:21
@greenerk It's related to the issue.  They're pointing out that entering a space via double spacing does not produce the red underline bug.

**Comment by greenerk** [comment] 2022-01-28 08:27
Ah, fair enough. It was also mentioned my ezeeman in an earlier comment.

**Comment by tsaoi** [comment] 2022-01-31 05:32
Chiming in here - I have tried troubleshooting to no avail and toyed around with FlorisBoard.

I did notice that although it underlines words with a full stop (period) that has been manually entered, if you click the back arrow to go out to your Messages listing and **then** back into the draft message, the red lines disappear?! 
Unfortunately this includes blatantly misspelt words with or without the period, mind you.

Currently on Pixel 4a build number: SQ1A.220105.002.2022011423

From Settings | System | Languages & input:
Languages: English (UK)
On-screen keyboard: GrapheneOS Keyboard
Physical keyboard: Not connected
Spell checker: GrapheneOS Spell Checker

Look forward to seeing how this ends up! 
Keep up the great work Devs :)

**Comment by greenerk** [comment] 2022-04-08 17:08
Does anyone know if this is a wider issue with AOSP higher upstream or specific to GrapheneOS?
I have other devices I toy with, running other non-stock ROMs and GrapheneOS is the only one exhibiting this issue.
I'm surprised there aren't more users chiming in as I assumed it would be affecting all users.

**Comment by thestinger** [comment] 2022-04-09 02:07
It's an AOSP keyboard issue. We aren't applying a workaround for the issue since it causes system_server crashes. We need to switch to a different keyboard.

**Comment by greenerk** [comment] 2022-05-05 15:40
As this is an AOSP issue, does that mean that *everyone* will be experiencing this, or just this select few of us?
I want to reflash my phone fresh again (to see if that clears it), but not if the issue will remain.

**Comment by thestinger** [comment] 2022-08-31 08:46
Let us know if this is still an issue in Android 13.

**Comment by greenerk** [comment] 2022-08-31 09:01
Afraid so.  Auto-punctuation appears to be OK, it's when you enter a full-stop/period manually that the false red line gets triggered.

![signal-2022-08-31-095459](https://user-images.githubusercontent.com/56622533/187639926-9da66ec4-57cf-4e0f-8ec0-16b3fa06b5d2.jpeg)

I recently flashed a couple of other non-Pixel devices with Android 12 versions of LineageOS and /e/ ROMs, and the issue appeared on those too.  I'm surprised the wider Android community aren't screaming from the rooftops about it - do so many people just "not notice"?

**Comment by mbg-unsw** [comment] 2022-08-31 09:56
Could it be locale-dependent? My primary language is set to "English (Australia)" and similarly in the AOSP keyboard settings. Spell checker is set to "Use system languages".

**Comment by greenerk** [comment] 2022-08-31 10:08
Interesting thought. I've just played about with the language settings - Although mine is set to "English (UK)" the American spellings of words are **not** highlighted as incorrect, but I'd expect them to be.

**Comment by greenerk** [comment] 2022-08-31 15:55
> Not a problem with Gboard.

I'm getting it on all keyboards now.

**Comment by oldmanonthebus** [comment] 2022-08-31 21:15
After trying a bunch of combinations on both the phone's language and the
keyboards, I get the same error everytime.  Only tried using Graphene's
keyboard.

**Comment by Injectionation** [comment] 2022-09-02 16:14
> Afraid so. Auto-punctuation appears to be OK, it's when you enter a full-stop/period manually that the false red line gets triggered.
> 
> ![signal-2022-08-31-095459](https://user-images.githubusercontent.com/56622533/187639926-9da66ec4-57cf-4e0f-8ec0-16b3fa06b5d2.jpeg)
> 
> I recently flashed a couple of other non-Pixel devices with Android 12 versions of LineageOS and /e/ ROMs, and the issue appeared on those too. I'm surprised the wider Android community aren't screaming from the rooftops about it - do so many people just "not notice"?

Oh we notice. Pixel 5a on android 13, US English, GrapheneOS stock keyboard. The incorrect underlines still pop up when double spacing after a word, and also when manually placing a period through the keyboard and then spacing away from it.

**Comment by Obezyana33** [comment] 2023-03-12 02:55
I just migrated from /e/ OS Android 12, which did not have this issue, but Graphene does. Is there really no workaround or fix in all this time?

Pixel 5
Android 13 (TQ1A.230205.002.2023030400)
Anysoft
English (Australia)

**Comment by thestinger** [comment] 2023-03-12 03:09
It's not a GrapheneOS specific issue. It's an AOSP and stock Android OS issue impacting certain locales with keyboards not providing their own spell checking functionality.

**Comment by tokenwizard** [comment] 2023-03-15 19:08
This happens to me on GrapheneOS on my Pixel phone but also in Lineage on my Xiaomi phone. Does not matter the keyboard being used in either case. Auto-punctuation via double-space is fine. Manually-entered punctuation causes the preceding word to be highlighted as misspelled.

**Comment by r3g-5z** [comment] 2023-04-04 00:39
Should be solved in next GrapheneOS release (April security update).

**Closed as completed by r3g-5z** 2023-04-04 00:39 UTC
Labels: bug, upstream
